type User {
  age: Int
  salary: Float
  name: String
  active: Boolean
  id: ID
  phone: String
  profile: Profile
  profile_id: Int
}

input UserInput {
  salary: Float
  name: String
  phone: String
}

type Query {
  user(id: Int, name: String): User
  users: [User!]!
}

type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: Int!, data: UserInput): User!
}
